### PR TITLE
Wrapping raw SQL in Arel.sql() 

### PR DESCRIPTION
**Pull request by glasses618**
Since Rails 5.2 https://github.com/rails/rails/pull/27947, some kind of raw SQL in `ActiveRecord::QueryMethods#order` should be wrapped in `Arel.sql()` or will get `DEPRECATION WARNING`. And Since Rails 6.1  https://github.com/rails/rails/commit/317465a4a8f8c0ebaf9534921350c4540584c03c, it will raise `ActiveRecord::UnknownAttributeReference` error anyway.
This PR wrapping raw SQL in `Arel.sql()` for MySQL SQLs. It should be fine for PostgreSQL SQLs.

### CODE REVIEW

**Comment by khiav223577** [comment]
Thanks! It also looks like it is required in Rails 6.1.
https://api.rubyonrails.org/classes/ActiveRecord/UnknownAttributeReference.html

The CI is broken. Could you rebase the branch to latest master? 
I had fixed it in the following PRs:
- https://github.com/khiav223577/find_with_order/pull/25
- https://github.com/khiav223577/find_with_order/pull/26

**Comment by glasses618** [comment]
> Thanks! It also looks like it is required in Rails 6.1. https://api.rubyonrails.org/classes/ActiveRecord/UnknownAttributeReference.html
> 
> The CI is broken. Could you rebase the branch to rebase to latest master? I had fixed it in the following PRs:
> 
> * [Fix error: unknown type name ‘my_bool’; did you mean ‘bool’? #25](https://github.com/khiav223577/find_with_order/pull/25)
> * [Skip the step of publishing code coverage for the PR from forked repos #26](https://github.com/khiav223577/find_with_order/pull/26)

I have rebased the branch to the latest master!

**Comment by khiav223577** [comment]
Looks great!

**Comment by khiav223577** [comment]
Just release v1.3.1!
See the [CHANGELOG](https://github.com/khiav223577/find_with_order/blob/master/CHANGELOG.md) for more details.

**Comment by glasses618** [comment]
> Just release v1.3.1! See the [CHANGELOG](https://github.com/khiav223577/find_with_order/blob/master/CHANGELOG.md) for more details.

Thanks!

**Pull request merged**
